mathiasdup/clicknfood

app/controllers/meals_controller.rb
app/views/meals/index.html.erb
app/views/meals/show.html.erb

Ajout de la fonctionnalité index et show - sans design
+ filtre location et category

Show et index created

---

app/controllers/users_controller.rb
app/policies/order_policy.rb
app/policies/user_policy.rb
app/views/users/profile.html.erb

Ajout partiel : Profil utilisateur (50%)
Reste à faire : Profil utilisateur (acces aux commandes)
Require : order_controller

AJOUT DE INTERFACE UTILISATEUR

---

app/views/meals/new.html.erb

Add the form to create a new meal

Add Meal new/create

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/components/_footer.scss
app/views/pages/home.html.erb

creation et style des cartes de meals

cards style

---

app/models/meal.rb
app/views/meals/new.html.erb

creation d'une liste de category pour les meals

creation de liste de category

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_footer.scss
app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/views/pages/home.html.erb

creation de cards selon les meals enregistrés

cards selon meal

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_footer.scss
app/views/pages/home.html.erb

Form sur Home page with form_with

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_profilecards.scss
app/assets/stylesheets/config/_fonts.scss
app/views/users/profile.html.erb

FAIT : PROFIL UTILISATEUR COMPLET AVEC LIENS
A POURSUIVRE : AJOUT DE L AVATAR + COMPLETER CSS

USER PROFILE COMPLETE -without avatar

---

app/assets/stylesheets/application.scss
app/views/users/profile.html.erb

Bug fixed for the profile display (orders)

Bug profile orders fixed

---

.gitignore
Gemfile
app/controllers/meals_controller.rb
app/models/user.rb
app/views/meals/new.html.erb
app/views/meals/show.html.erb
app/views/orders/show.html.erb
app/views/pages/home.html.erb
db/seeds.rb

Add images seed

---

.gitignore
app/assets/stylesheets/components/_search-bar.scss
app/assets/stylesheets/pages/_index.scss
app/views/meals/index.html.erb
app/views/shared/_navbar.html.erb

add style on meal index

---

.gitignore
app/assets/stylesheets/components/_global.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/meals/show.html.erb

design de la page show meal terminé

show meal fini

---

db/seeds.rb

juste créer des descriptions dans les plats

creationde descriptions

---

app/assets/stylesheets/components/_global.scss

fix design show meal

---

app/assets/stylesheets/components/_cards.scss
app/views/users/profile.html.erb

réglage placement du profil

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/components/_menu.scss
app/assets/stylesheets/components/_search-bar.scss
app/assets/stylesheets/pages/_index.scss
app/views/meals/index.html.erb

Delete banner
add css grid
add div to put a menu on the left

first step of index design

---

app/assets/stylesheets/components/_formulaire.scss
app/views/users/nepastouchermathias.html.erb

FORMULAIRE A FINIR MAIS LE CSS EST FAIT

FORMULAIRE BLOC

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_index.scss
app/controllers/meals_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/algoliadisplay.js
app/javascript/plugins/algoliasearch.js
app/models/meal.rb
app/views/layouts/application.html.erb
app/views/meals/index.html.erb
app/views/pages/home.html.erb
config/initializers/algoliasearch.rb
package.json
yarn.lock

Algolia implemented - need bundle install and algolia account - css to be reviewed

Algolia search

---

app/assets/stylesheets/components/_formulaire.scss
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/meals/new.html.erb

formulaire terminado

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_global.scss
app/controllers/application_controller.rb
app/controllers/reviews_controller.rb
app/controllers/users_controller.rb
app/models/meal.rb
app/models/user.rb
app/views/meals/show.html.erb
app/views/orders/_sharereview.html.erb
db/seeds.rb

affichage reviews et finish design meal show

Redesign meal

---

app/assets/stylesheets/components/_global.scss

add padding

---

app/assets/stylesheets/components/_formulaire.scss
app/views/reviews/new.html.erb

formulaire rating done

---

app/controllers/orders_controller.rb
app/controllers/reviews_controller.rb
app/views/layouts/application.html.erb
app/views/meals/show.html.erb
app/views/orders/_sharereview.html.erb
app/views/shared/_navbar.html.erb

alert messages ok

---

app/models/meal.rb
db/seeds.rb

Seed + change in category meal model
